$wall_path = /home/amit/.config/hypr/assets/walls/a_city_in_the_rain.jpeg
$font_family = JetBrainsMono Nerd Font ExtraBold

general {
		monitor = 
		grace = -1
		hide_curosr = false
		disable_loading_bar = false
}
background {
    	monitor = 
    	path = $wall_path
    	color = rgba(25, 20, 20, 1.0)
    	blur_passes = 1
}

label {
		monitor = 
		text = cmd[update:1000] echo $(/home/amit/.config/hypr/bin/capslock-status.sh)
		font_size = 20
		position = 0, -200
		halign = center
		valign = center
}

label {
		monitor = 
		text = cmd[update:1000] echo $(date +%A)
		font_size = 70
		font_family = Higher Jump
		position = 0, 300 
		halign = center
		valign = center
}

label {
		monitor = 
		text = cmd[update:1000] echo $(date +%T)
		font_size = 35
		font_family = $font_family
		halign = center
		valign = center
}

input-field {
    	monitor = 
    	size = 300, 300 
    	outline_thickness = 14
    	dots_size = 0.25
    	dots_spacing = 0.35
    	inner_color = rgba(0, 0, 0, 0.0) # no fill
    	placeholder_text = <i></i>
		fail_text = <i></i>
    	outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    	check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    	fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
    	font_color = rgb(143, 143, 143)
    	fade_on_empty = false
		capslock_color = rgba(ff6633ee)
    	halign = center
    	valign = center
    	rounding = -1
    	hide_input = true
}

shape {
		monitor = 
		size = 1920, 70
		color = rgba(255, 255, 38, 0.1)
		rounding = -1
		position = 0, 7
		halig = left
		valign = bottom
}

image {
    	monitor = 
    	path = $HOME/.config/hypr/assets/user.png
    	size = 100
    	position = 0, 7
    	valign = bottom
		halign = left
}

label {
    	monitor = 
    	text = cmd[update:10000000] echo Hello, ${USER^^}
    	font_size = 25
    	font_family = $font_family
    	position = 130, 20
    	halign = left
    	valign = bottom
}